
package Kasir;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import Kasir.Barang;

public class Table extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Table.class.getName());

    /**
     * Creates new form Frame2
     */
    public Table() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Load = new javax.swing.JButton();
        Insert = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Harga", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setHeaderValue("Kode");
            Table.getColumnModel().getColumn(1).setResizable(false);
            Table.getColumnModel().getColumn(1).setHeaderValue("Nama");
            Table.getColumnModel().getColumn(2).setResizable(false);
            Table.getColumnModel().getColumn(2).setHeaderValue("Harga");
            Table.getColumnModel().getColumn(3).setResizable(false);
            Table.getColumnModel().getColumn(3).setHeaderValue("Stock");
        }

        Load.setText("Load");
        Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadActionPerformed(evt);
            }
        });

        Insert.setText("Insert");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Load, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Load)
                    .addComponent(Insert)
                    .addComponent(Update)
                    .addComponent(Delete))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
    JTextField kodeField = new JTextField(5);
    JTextField namaField = new JTextField(15);
    JTextField hargaField = new JTextField(6);
    JTextField stockField = new JTextField(5);

    JPanel inputPanel = new JPanel();
    inputPanel.setLayout(new FlowLayout(FlowLayout.LEFT));
    inputPanel.setBackground(new Color(190, 190, 200)); // Sesuai screenshot

    inputPanel.add(new JLabel("Kode"));
    inputPanel.add(kodeField);
    inputPanel.add(new JLabel("Nama"));
    inputPanel.add(namaField);
    inputPanel.add(new JLabel("Harga"));
    inputPanel.add(hargaField);
    inputPanel.add(new JLabel("Stock"));
    inputPanel.add(stockField);

    int result = JOptionPane.showConfirmDialog(
        this,
        inputPanel,
        "Masukkan Data Produk Baru",
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.PLAIN_MESSAGE
    );

    if (result == JOptionPane.OK_OPTION) {
        try {
            int kode = Integer.parseInt(kodeField.getText());
            String nama = namaField.getText();
            int harga = Integer.parseInt(hargaField.getText());
            int stock = Integer.parseInt(stockField.getText());

            try (Connection conn = Koneksi.getConnection()) {
                String query = "INSERT INTO products (kode, nama, harga, stock) VALUES (?, ?, ?, ?)";
                PreparedStatement ps = conn.prepareStatement(query);
                ps.setInt(1, kode);
                ps.setString(2, nama);
                ps.setInt(3, harga);
                ps.setInt(4, stock);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
                LoadActionPerformed(null); // refresh tabel
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input tidak valid. Pastikan semua angka benar.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal insert ke database: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_InsertActionPerformed

    private void LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadActionPerformed
         try (Connection conn = Koneksi.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM products")) {

            DefaultTableModel model = (DefaultTableModel) Table.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                Barang barang = new Barang(
    rs.getInt("kode"),
    rs.getString("nama"),
    rs.getInt("harga"),
    rs.getInt("stock")
);

model.addRow(new Object[] {
    barang.getKode(),
    barang.getNama(),
    barang.getHarga(),
    barang.getStock()
});

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }//GEN-LAST:event_LoadActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
          String input = JOptionPane.showInputDialog(this, "Masukkan Kode Produk untuk Update:");
        if (input == null || input.trim().isEmpty()) return;

        try (Connection conn = Koneksi.getConnection()) {
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM products WHERE kode = ?");
            ps.setInt(1, Integer.parseInt(input));
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                JTextField namaField = new JTextField(rs.getString("nama"));
                JTextField hargaField = new JTextField(String.valueOf(rs.getInt("harga")));
                JTextField stockField = new JTextField(String.valueOf(rs.getInt("stock")));

                JPanel panel = new JPanel(new GridLayout(3, 2));
                panel.add(new JLabel("Nama:")); panel.add(namaField);
                panel.add(new JLabel("Harga:")); panel.add(hargaField);
                panel.add(new JLabel("Stock:")); panel.add(stockField);

                int result = JOptionPane.showConfirmDialog(this, panel, "Update Produk", JOptionPane.OK_CANCEL_OPTION);
                if (result == JOptionPane.OK_OPTION) {
                    PreparedStatement updatePs = conn.prepareStatement("UPDATE products SET nama=?, harga=?, stock=? WHERE kode=?");
                    updatePs.setString(1, namaField.getText());
                    updatePs.setInt(2, Integer.parseInt(hargaField.getText()));
                    updatePs.setInt(3, Integer.parseInt(stockField.getText()));
                    updatePs.setInt(4, Integer.parseInt(input));
                    updatePs.executeUpdate();
                    LoadActionPerformed(null);
                    JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Produk tidak ditemukan.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal update: " + e.getMessage());
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
              String input = JOptionPane.showInputDialog(this, "Masukkan Kode Produk untuk Hapus:");
        if (input == null || input.trim().isEmpty()) return;

        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

         try (Connection conn = Koneksi.getConnection()) {
            PreparedStatement ps = conn.prepareStatement("DELETE FROM products WHERE kode = ?");
            ps.setInt(1, Integer.parseInt(input));
            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                LoadActionPerformed(null);
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
            } else {
                JOptionPane.showMessageDialog(this, "Data stok yang akan dihapus tidak ada." );
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus: " + e.getMessage());
             
        }
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
   try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Table().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Insert;
    private javax.swing.JButton Load;
    private javax.swing.JTable Table;
    private javax.swing.JButton Update;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
